### ISSUE TITLE
Läuft das Projekt

### ISSUE THREAD

**Issue by Tiefflieger** [m31l3r/STM32F4_FOC#1]
Hallo,
ich gehe gerade davon aus, dass du deutsch sprichst. Aktuell möchte ich selbst eine Feldorientierte Regelung auf einem STM32F4 umsetzen. Ist dieses Projekt zur Regelung einer ASM eingesetzt worden?
In der IRQ Datei ist beispielsweise die Theta Berechnung auskommentiert. 
Ich wüsste daher gerne ob dies der finale Stand ist.
Danke!

**Comment by m31L3r** [comment]
Hallo Tiefflieger,
da es sich hier um eine Projektarbeit für die Uni handelt, würde ich nicht sagen, dass es so eingesetzt wird.
Der finale Stand ist es insofern, da wir die Arbeit längst abgegeben haben. Für industrielle Zwecke ist es so aber definitiv ungeeignet.
Ursprünglich war geplant das ganze auf eine Synchronmaschine anzuwenden, die zum Zeitpunkt der Fertigstellung aber nicht zur Verfügung stand. Daher haben wir den Wechselrichter gegen eine Drossel laufen lassen und 'nur' getestet ob er korrekten Drehstrom liefert. Dazu mussten wir aber eine Drehzahl vorgeben, was wir über feste Werte für Theta erreicht haben. Deswegen ist die Winkelmessung ausgegraut, weil wir keinen Drehgeber zu messen hatten sondern den Winkel vorgegeben haben.

Hoffe ich konnte weiterhelfen.

**Comment by Tiefflieger** [comment]
Hallo Michael,
mein Name ist übrigens Timo. Wir haben die gleich Situation, dass wir ein Projekt an der Hochschule umsetzen wollen. Über welche IDE wurde das ganze erstellt? Vielen Dank soweit.

**Comment by m31L3r** [comment]
Ich hab damals ausschließlich mit Eclipse und dessen C/C++ Plugin unter Linux gearbeitet.
Ansonsten ebenfalls nur OpenSource Software wie den GNU debugger und GCC, bzw. GNU Arm Embedded Toolchain. (https://developer.arm.com/open-source/gnu-toolchain/gnu-rm)

**Comment by Tiefflieger** [comment]
Alles klar, die IDE/Toolchain nutze ich auch unter Windows. Könntest du uns das Eclipse Projekt zur Verfügung stellen? Bei unserem Projekt sind noch weitere Treiber vorhanden die von STMCubeMX erzeugt wurden.

**Comment by m31L3r** [comment]
https://www.dropbox.com/sh/0ye987kt0mfvras/AADHUonwXK0Q8Q17vO1YRc0sa?dl=0
Mehr hab ich leider nicht mehr.
Die von STMCubeMX erzeugte Datei müsste in etwa das gleiche sein wie pinmux.c.

**Comment by Tiefflieger** [comment]
Cool, vielen Dank!

**Comment by Tiefflieger** [comment]
Hallo ich habe nun seit längerem Zeit gefunden mich mit dem Projekt zu beschäftigen. 
Meine Stromregelung läuft zur Zeit wie folgt ab:

/* Calculates I_alpha and I_beta */
current_a = (float32_t)Measure_Current1;
current_b = (float32_t)Measure_Current2;
arm_clarke_f32(current_a, current_b, &current_alpha, &current_beta);

/* Calculates sine and cosine for park transformation */
arm_sin_cos_f32(Theta, &sinevalue, &cosinevalue);

/* Park Transformation */
/* Calculates Id and Iq */
arm_park_f32(current_alpha, current_beta, &current_Id, &current_Iq, sinevalue, cosinevalue);

 /* Control Iq und Id and return Uq und Ud */
Uq = PI_control(Iq_Soll, current_Iq); //Ki und Kp evtl. anpassen
Ud = PI_control(Id_Soll, current_Id);

/* Transform Uq und Ud in U_alpha und U_beta*/
arm_inv_park_f32(Ud, Uq, &U_alpha, &U_beta, sinevalue, cosinevalue);

svpwm();
htim1.Instance->CCR1 = *switchtime[0];
htim1.Instance->CCR2 = *switchtime[1];
htim1.Instance->CCR3 = *switchtime[2];
Der Ablauf wird mit 20kHz aufgerufen und erzeugt PWM auf den Ausgängen. Allerdings komme ich gerade nicht drauf, wie der Bezug zwischen der Timer Period mit 5250 und der Switchtime ist. Bei Switchtime erhalte ich Werte bis 65535, wie muss ich das abstimmen damit beide Auflösungen zusammenspielen?
EDIT: 
nutze nun eine andere SVPWM
